### ISSUE TITLE
jsx-control-statements with babel standalone

### ISSUE THREAD

**Issue by elennaro** [Daniel15/babel-standalone#11]
How can I use the plugin that is not included, like [jsx-control-statements](https://github.com/AlexGilleran/jsx-control-statements). I'd really appreciate any help.

**Comment by antivanov** [comment]
The following might work (did not try it myself). From the source code it seems that you can try to require the desired plugin and pass it in the Babel options:

```
var options = {
  presets: ['react'],
  plugins: [require('jsx-control-statements')]
}
...
var transpiled = Babel.transform(input, options).code;
...
```

**Comment by elennaro** [comment]
@antivanov thank you.
I use it from nashorn, so I've forked babel-standalone and injected jsx-control-statements.

**Comment by Daniel15** [comment]
Sorry I didn't reply sooner! Loading extra plugins really depends on your environment. If you have a working CommonJS environment (that is, `require`  works), then just `require`-ing it as @antivanov mentioned should work. Otherwise, you'd need to use something like Webpack or Browserify to bundle babel-standalone along with any extra plugins you want to use.

**Comment by elennaro** [comment]
@Daniel15 thank you.
