### ISSUE TITLE
Safari gives "ERROR: unknown: Property id of VariableDeclarator expected node"

### ISSUE THREAD

**Issue by streets-ahead** [Daniel15/babel-standalone#19]
Safari is giving an error: ERROR: unknown: Property id of VariableDeclarator expected node.  But this bug is extremely strange.  First it only happens in Safari with the console closed, if I open the console its fine.  Second, I've boiled it down to the following simple code showing the issue:

```
 class A extends React.Component {
      render() {
        return (
          <div>
            <div>Test</div>
            <input type="checkbox" value={this.props.value} onChange={{}} />
            <div style={{border: "1px solid #ddd"}}>test</div>
          </div>
        );
      }
    }

    class B extends React.Component {
      render() {
        return (
          null
        );
      }
    }
```

Its really strange, if I remove for example, the <input> tag, it starts working.  Also if I change the order of the classes it starts working.  I've attached the test file I am using, its a modified version of the sample included with this project.

[example.htm.zip](https://github.com/Daniel15/babel-standalone/files/141553/example.htm.zip)

**Comment by Daniel15** [comment]
Given its very low market share, I don't really have time to look into issues that are specific to Safari (much in the same way that I no longer look into IE 6 and 7 issues). You could try filing this as a bug in the Babel bug tracker and see if anyone has any idea what's causing this, as it'll be some issue in the Babel code somewhere. It's possible it's a bug in Safari rather than a bug in Babel.
