### ISSUE TITLE
Browser support

### ISSUE THREAD

**Issue by weslleyaraujo** [Daniel15/babel-standalone#21]
Hi @Daniel15,

would be nice to have a browser support list at the `readme.md` file or somewhere :)

So far I have done some tests with `babel-standalone` and I could not make it run on IE8/IE9,
other browsers seems okay.

**Comment by Daniel15** [comment]
You might need to load some polyfills in old IE. What errors were you encountering in IE9?

**Comment by weslleyaraujo** [comment]
So, I built babel from the last `babel-standalone` update (6.6.5)
and here are the details that I got so far:

```html
<script src="./babel.js"></script>
  <script>
    var code = ' const sum = (x, y) => x + y; export default sum; ';
    var babelOptions = {
      plugins: [
        'transform-es2015-modules-amd',
        'transform-es3-property-literals',
        'transform-es3-member-expression-literals',
      ],

      presets: [
        'es2015-loose',
      ],
    };

    var sum = Babel.transform(code, babelOptions).code;
    alert(sum);
  </script>
```

**IE9 non-minified babel**
![ie9_-_win7__running_](https://cloud.githubusercontent.com/assets/2286385/13568539/1f0600c0-e462-11e5-9523-1102e487bc2c.png)

**IE9 minified babel**
![ie9_-_win7__running_min](https://cloud.githubusercontent.com/assets/2286385/13568547/2541d9b4-e462-11e5-88fd-7e06b0e0f29a.png)

I still haven't done the test's with `babel-polyfill` included but I will gather more information and update here asap :D
btw, is there a "babel polyfill standalone" like to use on browser as well?

**Comment by Daniel15** [comment]
> btw, is there a "babel polyfill standalone" like to use on browser as well?

Babel polyfill is already standalone :) You can load it from CDNJS if you like (https://cdnjs.cloudflare.com/ajax/libs/babel-polyfill/6.7.4/polyfill.min.js).

**Comment by Daniel15** [comment]
Interesting, Babel is probably doing something that doesn't work in IE9. Note that Microsoft no longer support IE8, IE9 and IE10 so it's unlikely this will be fixed. I'm going to close this out since I don't plan on supporting IE versions that are no longer supported by Microsoft.

> btw, is there a "babel polyfill standalone" like to use on browser as well?

Babel polyfill is already standalone, by definition all polyfills need to be standalone and able to load in a browser :) You can load it from CDNJS if you like (https://cdnjs.cloudflare.com/ajax/libs/babel-polyfill/6.7.4/polyfill.min.js).
