### ISSUE TITLE
Using the plugin throws an error

### ISSUE THREAD

**Issue by voronianski** [Daniel15/babel-standalone#4]
I'm experimenting with your module in browser and I would like to use `transform-runtime` plugin. However for now it's impossible 'cause an error is thrown - `Uncaught ReferenceError: require is not defined`. It points to this line - `var _regenerator = require('babel-runtime/regenerator');` which is the code of plugin itself. Does this mean that your module needs deeply include/require all dependencies in order to be available in browser?

My code looks like:

```js
var options = { presets: ['es2015', 'react', 'stage-0'], plugins: ['transform-runtime'] };
var output = Babel.transform('let a = 2', options).code;
```

Thanks!

**Comment by danmartinez101** [comment]
Couple of things you can try here: 
1. use a direct require of the module into your options object as demonstrated in [throw-in-the-towel](https://github.com/danmartinez101/throw-in-the-towel/blob/master/index.js#L50)

2. try including the transform-regenerator plugin as well

**Comment by Daniel15** [comment]
Hmm, seems like I need to do some more testing of `transform-runtime`. Thanks for the report, I'll try to look at this over the weekend.

**Comment by Daniel15** [comment]
So I looked into this, and by definition I don't think there's any useful way to use `transform-runtime` with `babel-standalone`. `transform-runtime` requires a module system of some sort (eg. CommonJS). I think you'd need to load a module plugin other than `transform-es2015-modules-commonjs` if you wanted to use it.

It looks like `transform-runtime` loads polyfills and external helpers, rather than requiring you to polyfill globally. I'm not sure that's useful with babel-standalone, you should just be polyfilling :). For externalising helpers to save bytes, you could use `external-helpers-2`.

Closing this out, but let me know if you disagree :)
