### ISSUE TITLE
Support preset options for the bundled presets

### ISSUE THREAD

**Issue by Kovensky** [Daniel15/babel-standalone#49]
Right now, if, for example, `[ [ "es2015", {} ] ]` is given to plain `babel-standalone` in a browser, it causes babel to error out as it `Couldn't find preset "es2015" relative to directory "."`.

**Comment by Daniel15** [comment]
Should be straightforward to do, just need to modify the code at https://github.com/Daniel15/babel-standalone/blob/master/src/index.js#L25 to handle the value being an array.

**Comment by taion** [comment]
This should probably come with bumping the minimum Babel version to 6.13 in package.json.

**Comment by Kovensky** [comment]
Wrote https://github.com/Daniel15/babel-standalone/pull/50 to implement this; also added support for passing options to plugins.

The package.json already requests `babel-core` and `babel-preset-es2015` ^6.13.2.

**Comment by taion** [comment]
Oh, neat, didn't see that package.json got bumped.

**Comment by Daniel15** [comment]
Yeah I've got a somewhat-automated process for bumping versions in `package.json` and automatically releasing new builds as long as the unit tests pass. Haven't committed all the code for that yet though. One thing I should do is change the package.json to use exact package versions rather than ranges, as I always want these builds to be repeatable and use the exact same version of Babel.

**Comment by Daniel15** [comment]
Added in #50, thanks @Kovensky!
